### ISSUE TITLE
upgrade version for ice-g2p

### ISSUE THREAD

**Issue by lumpidu** [tiro-is/tiro-tts#2]
The Python module for ice-g2p is rather old. It should be updated to a newer one

**Comment by rkjaran** [comment]
With the merge [ef2b60b526826d7536180fd2a6dcd3feb3b19227](https://github.com/tiro-is/tiro-tts/commit/ef2b60b526826d7536180fd2a6dcd3feb3b19227) we now use [ice-g2p@bc145b77b92cf1f05edd69fc54f7cced8877f471](https://github.com/grammatek/ice-g2p/commit/bc145b77b92cf1f05edd69fc54f7cced8877f471) which were the most recent changes when this issue was created.
